
client_config_backend: file
client_config:
    client_id: 506721459045-727nmn8ojphcmakv6g3i6mk7no497ggm.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive